### PR TITLE
Rubocop cleanup

### PR DESCRIPTION
**Pull request by djberg96**
This PR is mainly the results of `rubocop -a` applied to the various Ruby files. At the time of this PR I am using rubocop 0.83. The only hand edits I made were to the Rakefile, where I added a post-spec cleanup task so that various C compilation files weren't laying around afterwards.

Note that I intentionally created separate commits so that I could delete that commit if you have issues with only certain file changes. I can squash these all down later to a single commit as desired.

If you're not a fan of the changes that rubocop made, might I suggest adding a .rubocop.yml file to the project that adjusts the style to your liking?

### CODE REVIEW

**Comment by threez** [comment]
To be honest, I'm not the biggest fan of rubocop. I don't really understand the purpose of these changes. Why would you change the formatting of a code that works since many years?

**Comment by djberg96** [comment]
@threez Not all of these changes are purely aesthetic, some of these are best practices collected over many years of experience. I'll try to go over these and explain the rationale for the changes.

* The `frozen_string_literal` pragma has been available since Ruby 2.3 and improves performance where you have immutable data. Since you're reporting data from the operating system, this seems like a good idea. In Ruby 3.x, this will actually be the default behavior.

http://flats.github.io/blog/2016/01/03/frozen-strings/

* You also have some trailing whitespace. Why not remove it? It's wasted bytes.

* Using an underscore for unused block variables is a good idea so that you don't accidentally shadow it. An unused variable will also emit a warning if warnings are turned on.

* `$LOAD_PATH` is easier to read than `$:`, don't you think?

* The Rakefile adjustments were actually my idea and not rubocop, I just tossed them in here because I thought they were a good idea.

Admittedly, the single-quotes vs double-quotes is purely cosmetic, as are the indentation changes. So, the reason to have your own .rubocop.yml file then is so that people who submit contributions can conform to your coding style. It's not strict enforcement, so if you want to ignore the rubocop warnings (which github will automatically show you) you can, but you also then ask people to update their PR's to comply with your code formatting standards. They'll also be able to see right away what rubocop complained about.

On top of all that, if you ran rubocop locally, you would see that there were a few warnings that it didn't fix because they would require more significant changes. Specifically, rubocop let me know that the way you're subclassing structs is generally considered bad practice because it injects a useless anonymous subclass into the ancestry tree.

```
irb(main):003:0> Vmstat::Cpu.ancestors
=> [Vmstat::Cpu, #<Class:0x000055a3a1642b08>, Struct, Enumerable, Object, Kernel, BasicObject]
```
Researching this led me to articles like this:

https://thepugautomatic.com/2013/08/struct-inheritance-is-overused/

There's also named parameters for structs now, too, not sure if that interests you.

Anyway, you're free to take or ignore any of this advice as you see fit. I can update the PR, or close it, as you prefer.

**Comment by threez** [comment]
Thanks for the time you took to explain the changes. I unterstand that you want to improve the code base by changing everything into rubocop best practices.

To me this changes show no real enhancement of the codebase in itself. 
But they will require testing again on every supported OS.

I want to understand what these changes do prepare. What are the changes you intend to do for which these changes are helpful?

**Comment by threez** [comment]
Closed due to inactivity, we re-open when we find an answer to the question above.

**Pull request closed without merging**
