### PR TITLE
Convert specs from rpsec version 2 to rspec version 3.

### PR DESCRIPTION
**Pull request by djberg96**
RSpec 3 has been out quite a while, and running the specs currently generates a few warnings about the old "its" syntax. This PR updates the specs to the version 3 syntax (expect vs should), and eliminates the warnings.

I also updated the gemspec and Gemfile.lock, and removed a deprecated setting from spec_helper.rb.

This update made possible by https://github.com/yujinakayama/transpec

### CODE REVIEW

**Comment by threez** [comment]
@djberg96 du you have an updated Gemfile.lock locally? Maybe that is the cause for the failing specs.

**Comment by djberg96** [comment]
@threez The one I have locally is the one I pushed up as part of this PR (minus the `x86_64-darwin-19` platform, but it fails with or without it).

What am I supposed to do here?

**Comment by djberg96** [comment]
@threez I just decided to remove the Gemfile.lock from the git repo. I hope that was ok. I think for standalone libraries it's not really useful, and leads to headaches like this.

**Comment by threez** [comment]
@djberg96 the changes look good, but I have a different opinion regarding the Gemfile.lock. It helps that the CI is consistent with the local builds across many envrionments (e.g. when working with many operating systems). Did you figure out why the build was failing exactly? Maybe the fix was removing the bundler dependency and not the Gemfile.lock

**Comment by djberg96** [comment]
A committed Gemfile.lock is a constant source of heartache in my experience, and for small libraries like this, not really essential. But, of course, it's your library to manage as you see fit. :)

I never did figure out why it was failing, but it failed before I added the bundler dependency. I could try adding a bundler 1.x dependency. Otherwise, I'm not sure.

**Comment by djberg96** [comment]
@threez ok, I put it back, but don't know how to fix the error.

**Comment by djberg96** [comment]
@threez Ok, looks like I got it working. In the end I ended up:

* Switching to Linux
* Downgrading to bundler 1.17
* Rebuilding the Gemfile.lock and pushing it.

No clue why trying to force bundler 2 didn't work, but here we are.

**Comment by threez** [comment]
@djberg96 great job, you did it. Thanks! MR Looks good.

**Pull request merged**
